# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eac84b64143a48daf85ed9cfd1f669c991344e0014f15a1307c33dbc73aed507f9fec5c33cc4ded3fcc0759befed6ac538a3b3ab6ad041ec2997b5ecaff2709

test:
  secret_key_base: 87646366acd55301ffd8c3f472537b995cfb9f2202bd978eef0663f82f7533d3fd9cbc1f2a286f8e212d0d3da926a5facb83c572bbbfc207829e51d457d5b8e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
